### ISSUE TITLE
Release 0.3.0 proposal

### ISSUE THREAD

**Issue by nerro** [nerro/javinla#13]
- Issues:
  - [x] #7 - Research if bats can be used
  - [x] #10 - Add Travis CI integration
  - [x] #12 - Improve documentation for the project
- Documentation:
  - [x] prepare release notes

**Comment by nerro** [comment]
Release notes added.
LGTM
