### ISSUE TITLE
Release 1.0.0 proposal

### ISSUE THREAD

**Issue by nerro** [nerro/javinla#14]
- Issues:
  - [x] #15 - Add bats tests to the project
  - [x] #16 - Add new java versions (`8u101`)
  - [x] #17 - Add new java versions (`8u111`, `8u112`)
- Documentation:
  - [x] prepare release notes

**Comment by nerro** [comment]
done.
